### ISSUE TITLE
ContentRepository must be of type Countable|array, null given

### ISSUE THREAD

**Issue by Mordef** [IchHabRecht/content_defender#131] opened 2023-03-29 11:46 UTC
Typo3 v11.5.25
PHP 8.1

Blank Page, insert 2 Elements Textmedia and try to reorder

```
count(): Argument #1 ($value) must be of type Countable|array, null given
... typo3conf/ext/content_defender/Classes/Repository/ContentRepository.php line 73
``` 

It works with (Line 73)
```php
return count($this->colPosCount[$identifier] ?? []);
```

**Comment by IchHabRecht** [comment] 2023-04-08 08:39
Hi @Mordef,

I tried to reproduce the problem in a current TYPO3 11.5 installation with PHP 8.1.9 but I don't get the Exception. System is in development mode and error handling is set to debug as well. Can you give me a step by step instruction what you are doing? Is there any pageTS on that page? Are you using an admin or user account?

**Comment by IchHabRecht** [comment] 2023-04-08 08:40
Duplicate of #130

**Comment by zwenn** [comment] 2023-05-05 08:06
I was able to reproduce the Exception.

In development, all caches are disabled and the Exception is thrown.
In production, caches are enabled an no Exception is thrown.

Hope this will help.

**Comment by IchHabRecht** [comment] 2023-05-05 08:26
Hi @zwenn 

Thank you for your answer. Unfortunately it doesn't help in any way for me to reproduce the problem. As you may saw, I asked about several questions in my comment above. maybe you can take some time and give me additional information about your environment.

**Comment by zwenn** [comment] 2023-05-05 08:39
Hi,

Typo3v11.5.26
PHP8.2
content_defender 3.3.0

// Disable all Caches in Development
// https://medium.com/typo3blog/disabling-typo3-caches-a137667848c9
    foreach ($GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'] as $cacheName => $cacheConfiguration) {
        $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][$cacheName]['backend'] = NullBackend::class;
    }

$GLOBALS['TYPO3_CONF_VARS']['SYS']['displayErrors'] = 1;
$GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = 1;
$GLOBALS['TYPO3_CONF_VARS']['FE']['debug'] = 1;

**Comment by IchHabRecht** [comment] 2023-05-05 08:44
Hi @zwenn,

I already set all those settings in my test installation. Not sure if you saw my open questions from above "Can you give me a step by step instruction what you are doing? Is there any pageTS on that page? Are you using an admin or user account?"
Are you using a brand new TYPO3 system setup from scratch with only content_defender installed or are there any other extensions enabled? Maybe you can have a try in a fresh new installation and give me a step by step report of what you are doing?

**Comment by zwenn** [comment] 2023-05-05 09:03
Reproduction with admin user and normal beuser.
There are some mask elements on the pages.
Backend Layouts are configured with pageTs 
`mod.web_layout.BackendLayouts`

The current installation is an updated installation from 10.4.37.

I will test with a brand new installation and then give feedback.

**Comment by zwenn** [comment] 2023-05-07 09:12
After setting up a brand new Typo3v11.5.26 (legacy - non composer) System I did the following:

1. install content_defender 3.3.0
2. create new Page as root page [is_siteroot]
3. add PageTs

```
mod.web_layout.BackendLayouts {
  test {
    title = Test
    config {
      backend_layout {
        colCount = 1
        rowCount = 1
        rows {
          1 {
            columns {
              1 {
                name = Inhalt
                colPos = 0
                allowed {
                	CType = header
                }
                maxitems = 1
              }
            }
          }
        }
      }
    }
  }
}
```
4. choose as [backend_layout]
5. add content element [header] to page [colpos = 0]
6. in settings: Choose Preset -> Debug settings -> Debug [Active]
7. Set nginx Directive:
`fastcgi_param TYPO3_CONTEXT Development;`
8. add AdditionalConfiguration.php in typo3conf for disabling ALL caches
```
/**
 * Application Context: Development
 */
if (\TYPO3\CMS\Core\Core\Environment::getContext()->isDevelopment()) {
	
    // DEBUG MODUS
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['displayErrors'] = 1;
    $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = 1;
    $GLOBALS['TYPO3_CONF_VARS']['FE']['debug'] = 1;
	
    // Disable all Caches in Development
    // https://medium.com/typo3blog/disabling-typo3-caches-a137667848c9
    foreach ($GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'] as $cacheName => $cacheConfiguration) {
        $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][$cacheName]['backend'] = \TYPO3\CMS\Core\Cache\Backend\NullBackend::class;
    }
}
```
9. try to edit the content element

Tested under PHP7.4 and get this Exception (rename to .html)
[Exception-php74.txt](https://github.com/IchHabRecht/content_defender/files/11414375/Exception-php74.txt)

Tested under PHP8.0, 8.1, 8.2 and get this Exception (rename to .html)
[Exception-php80-82.txt](https://github.com/IchHabRecht/content_defender/files/11414376/Exception-php80-82.txt)

**Comment by IchHabRecht** [comment] 2023-05-08 09:05
Hi @zwenn,

Thank you for your information. I found the problem with your installation and maybe it's the same as @Mordef is using. You are disable the runtime cache which is a TransientMemoryBackend and should not be set to a NullBackend (thus you need to exclude the "runtime" cacheName in your configuration. content_defender needs this cache to be able to store the current count of available content elements for on colPos to ensure the maxitems count is working properly. I will add a note about the runtime cache to the README.md file of this project.

**Closed** 2023-06-19 10:14 UTC
Labels: duplicate, question
